name: neon_pong_revival
description: DeadmanXXXIIs Classic Pong - Neon Red Mobile Edition
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.6.0
  audioplayers: ^6.1.0
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/8-bit-loop-music-290770.mp3
    - assets/hit.wav
    - assets/over.wav
    - assets/icon.png

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
