
[tool.briefcase]
project_name = "DeadmanPong"
bundle = "com.deadman.pong"
version = "1.0.0"
url = "https://github.com/DeadmanXXXII/"
license = "MIT"
author = "DeadmanXXXII"
author_email = "deadmanxxxii@example.com"

[tool.briefcase.app.deadman_pong]
formal_name = "DeadmanXXXII's Classic Pong"
description = "A neon revival of classic Pong, with music, glow effects, and AI."
sources = ["src/deadman_pong"]
requires = ["pygame-ce", "toga"]
icon = "src/deadman_pong/assets/icon.png"

[tool.briefcase.app.deadman_pong.macOS]
requires = ["toga-cocoa"]

[tool.briefcase.app.deadman_pong.linux]
requires = ["toga-gtk"]

[tool.briefcase.app.deadman_pong.windows]
requires = ["toga-winforms"]

[tool.briefcase.app.deadman_pong.iOS]
requires = ["toga-iOS"]

[tool.briefcase.app.deadman_pong.android]
requires = ["toga-android"]
